name: Practice

on: 
  issues:
    types: [opened]
    
  workflow_dispatch:

jobs: 
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: node index.js
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Update Ubuntu
        run: |
          sudo apt update
          sudo apt install jq
      - name: Check the Github Event
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
