name: Practice

on: 
  issues:
    types: [opened]
    
  workflow_dispatch:

jobs: 
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: node index.js
  log-event:
    runs-on: ubuntu-latest
    steps:
      - name: Update Ubuntu
        run: |
          sudo apt update
          sudo apt install jq
      - name: Check the Github Event
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
